/**
 * Hand-written, FICTIONAL source data for the public demo.
 *
 * Every listing here is invented: the streets do not exist, the URLs point at `example.com`, the
 * landlords are made up and there are no photos. Only the cities are real, so the radar and the
 * map have something recognisable to work with. Nothing in this file was captured from a real
 * housing portal, and it must stay that way: the demo is public.
 *
 * `build-demo-dataset.ts` feeds these listings through the real API (against an in-memory
 * database), so the recorded responses still have exactly the API's shape.
 */
import { type CanonicalListing, canonicalKey, type RegistrySource, stableHash } from "@papa/core";

/**
 * Fictional sources, using the example slugs of `docs/sources/registry.yaml`. Only the fields the
 * `sources` table keeps are filled in.
 */
export const DEMO_SOURCES = [
  {
    slug: "example-portal",
    name: "Example Portal",
    kind: "consortium",
    stack: "bespoke",
    tier: "A",
    status: "live",
    interval_seconds: 300,
  },
  {
    slug: "example-portal-b",
    name: "Example Portal B",
    kind: "manager",
    stack: "bespoke",
    tier: "A",
    status: "live",
    interval_seconds: 600,
  },
] as unknown as RegistrySource[];

type Seed = {
  source: "example-portal" | "example-portal-b";
  id: string;
  street: string;
  houseNumber: string;
  city: string;
  municipality: string;
  province: string;
  lat: number;
  lng: number;
  segment: CanonicalListing["segment"];
  allocationModel: CanonicalListing["allocationModel"];
  priceNet: number;
  serviceCosts: number;
  rooms: number;
  bedrooms: number;
  areaM2: number;
  dwellingType: string;
  dwellingCategory: CanonicalListing["dwellingCategory"];
  energyLabel: string;
  constructionYear: number;
  floor: number | null;
  availableFrom: string | null;
  publishedAt: string;
  labels?: CanonicalListing["labels"];
  notices?: string[];
  eligibility?: CanonicalListing["eligibility"];
  reactionsCount: number | null;
  description: string;
};

const SEEDS: Seed[] = [
  {
    source: "example-portal",
    id: "VW-1001",
    street: "Denkbeeldstraat",
    houseNumber: "14",
    city: "Amsterdam",
    municipality: "Amsterdam",
    province: "Noord-Holland",
    lat: 52.3702,
    lng: 4.8952,
    segment: "midden",
    allocationModel: "loting",
    priceNet: 1085,
    serviceCosts: 45,
    rooms: 3,
    bedrooms: 2,
    areaM2: 68,
    dwellingType: "Bovenwoning",
    dwellingCategory: "apartment",
    energyLabel: "B",
    constructionYear: 1998,
    floor: 2,
    availableFrom: "2026-11-01",
    publishedAt: "2026-09-28T08:00:00.000Z",
    reactionsCount: 212,
    description:
      "Fictieve woning voor de demo. Lichte driekamerwoning op de tweede verdieping met balkon op het zuiden.",
  },
  {
    source: "example-portal-b",
    id: "DV-2001",
    street: "Proefkade",
    houseNumber: "3",
    city: "Amstelveen",
    municipality: "Amstelveen",
    province: "Noord-Holland",
    lat: 52.3114,
    lng: 4.8701,
    segment: "midden",
    allocationModel: "direct",
    priceNet: 1150,
    serviceCosts: 60,
    rooms: 2,
    bedrooms: 1,
    areaM2: 55,
    dwellingType: "Appartement",
    dwellingCategory: "apartment",
    energyLabel: "A",
    constructionYear: 2019,
    floor: 4,
    availableFrom: "2026-10-15",
    publishedAt: "2026-09-29T10:30:00.000Z",
    labels: ["nieuwbouw"],
    reactionsCount: null,
    description:
      "Fictieve woning voor de demo. Tweekamerappartement in een nieuwbouwcomplex, eerste reageerder krijgt een bezichtiging.",
  },
  {
    source: "example-portal",
    id: "VW-1002",
    street: "Fictieplein",
    houseNumber: "27",
    city: "Haarlem",
    municipality: "Haarlem",
    province: "Noord-Holland",
    lat: 52.3874,
    lng: 4.6462,
    segment: "midden",
    allocationModel: "inschrijfduur",
    priceNet: 995,
    serviceCosts: 38,
    rooms: 3,
    bedrooms: 2,
    areaM2: 72,
    dwellingType: "Benedenwoning",
    dwellingCategory: "apartment",
    energyLabel: "C",
    constructionYear: 1964,
    floor: 0,
    availableFrom: "2026-12-01",
    publishedAt: "2026-09-25T07:15:00.000Z",
    reactionsCount: 148,
    description:
      "Fictieve woning voor de demo. Benedenwoning met kleine tuin, toegewezen op inschrijfduur.",
  },
  {
    source: "example-portal",
    id: "VW-1003",
    street: "Verzonnenlaan",
    houseNumber: "88",
    city: "Utrecht",
    municipality: "Utrecht",
    province: "Utrecht",
    lat: 52.0907,
    lng: 5.1214,
    segment: "social",
    allocationModel: "inschrijfduur",
    priceNet: 712,
    serviceCosts: 32,
    rooms: 3,
    bedrooms: 2,
    areaM2: 64,
    dwellingType: "Portiekflat",
    dwellingCategory: "apartment",
    energyLabel: "B",
    constructionYear: 1972,
    floor: 1,
    availableFrom: null,
    publishedAt: "2026-09-27T06:00:00.000Z",
    reactionsCount: 389,
    description:
      "Fictieve woning voor de demo. Driekamerflat dicht bij het station, huurtoeslag mogelijk.",
  },
  {
    source: "example-portal",
    id: "VW-1004",
    street: "Schetsweg",
    houseNumber: "5",
    city: "Rotterdam",
    municipality: "Rotterdam",
    province: "Zuid-Holland",
    lat: 51.9244,
    lng: 4.4777,
    segment: "social",
    allocationModel: "loting",
    priceNet: 640,
    serviceCosts: 28,
    rooms: 2,
    bedrooms: 1,
    areaM2: 48,
    dwellingType: "Galerijflat",
    dwellingCategory: "apartment",
    energyLabel: "C",
    constructionYear: 1968,
    floor: 6,
    availableFrom: "2026-11-15",
    publishedAt: "2026-09-30T09:00:00.000Z",
    labels: ["jongeren"],
    notices: ["Alleen voor woningzoekenden tot 28 jaar"],
    eligibility: {
      minIncome: null,
      maxIncome: null,
      minAge: 18,
      maxAge: 27,
      minHousehold: null,
      maxHousehold: 2,
      localBindingPriority: null,
    },
    reactionsCount: 97,
    description:
      "Fictieve woning voor de demo. Jongerenwoning met uitzicht over de stad, verloting.",
  },
  {
    source: "example-portal",
    id: "VW-1005",
    street: "Modelhof",
    houseNumber: "41",
    city: "Den Haag",
    municipality: "'s-Gravenhage",
    province: "Zuid-Holland",
    lat: 52.0705,
    lng: 4.3007,
    segment: "social",
    allocationModel: "punten",
    priceNet: 815,
    serviceCosts: 40,
    rooms: 4,
    bedrooms: 3,
    areaM2: 86,
    dwellingType: "Eengezinswoning",
    dwellingCategory: "house",
    energyLabel: "A",
    constructionYear: 2004,
    floor: null,
    availableFrom: "2027-01-01",
    publishedAt: "2026-09-26T11:45:00.000Z",
    labels: ["grote_gezinnen"],
    eligibility: {
      minIncome: null,
      maxIncome: null,
      minAge: null,
      maxAge: null,
      minHousehold: 3,
      maxHousehold: null,
      localBindingPriority: null,
    },
    reactionsCount: 54,
    description:
      "Fictieve woning voor de demo. Eengezinswoning met drie slaapkamers, voorrang voor grote huishoudens.",
  },
  {
    source: "example-portal-b",
    id: "DV-2002",
    street: "Oefenstraat",
    houseNumber: "9",
    city: "Arnhem",
    municipality: "Arnhem",
    province: "Gelderland",
    lat: 51.9851,
    lng: 5.8987,
    segment: "midden",
    allocationModel: "optie",
    priceNet: 960,
    serviceCosts: 50,
    rooms: 3,
    bedrooms: 2,
    areaM2: 75,
    dwellingType: "Appartement",
    dwellingCategory: "apartment",
    energyLabel: "A",
    constructionYear: 2015,
    floor: 3,
    availableFrom: "2026-11-01",
    publishedAt: "2026-09-29T14:00:00.000Z",
    reactionsCount: 31,
    description:
      "Fictieve woning voor de demo. Ruim appartement met lift en berging, toewijzing op optie.",
  },
  {
    source: "example-portal",
    id: "VW-1006",
    street: "Bedachtsingel",
    houseNumber: "112",
    city: "Deventer",
    municipality: "Deventer",
    province: "Overijssel",
    lat: 52.2557,
    lng: 6.1636,
    segment: "social",
    allocationModel: "inschrijfduur",
    priceNet: 598,
    serviceCosts: 22,
    rooms: 2,
    bedrooms: 1,
    areaM2: 45,
    dwellingType: "Seniorenwoning",
    dwellingCategory: "senior",
    energyLabel: "B",
    constructionYear: 1990,
    floor: 0,
    availableFrom: "2026-10-20",
    publishedAt: "2026-09-24T08:30:00.000Z",
    labels: ["senioren", "nultreden"],
    notices: ["Woning voor 55+"],
    eligibility: {
      minIncome: null,
      maxIncome: null,
      minAge: 55,
      maxAge: null,
      minHousehold: null,
      maxHousehold: 2,
      localBindingPriority: null,
    },
    reactionsCount: 18,
    description: "Fictieve woning voor de demo. Gelijkvloerse seniorenwoning vlak bij het centrum.",
  },
  {
    source: "example-portal",
    id: "VW-1007",
    street: "Probeerpad",
    houseNumber: "7",
    city: "Zwolle",
    municipality: "Zwolle",
    province: "Overijssel",
    lat: 52.5168,
    lng: 6.083,
    segment: "social",
    allocationModel: "loting",
    priceNet: 745,
    serviceCosts: 30,
    rooms: 3,
    bedrooms: 2,
    areaM2: 70,
    dwellingType: "Tussenwoning",
    dwellingCategory: "house",
    energyLabel: "B",
    constructionYear: 1985,
    floor: null,
    availableFrom: "2026-12-15",
    publishedAt: "2026-09-30T07:00:00.000Z",
    reactionsCount: 266,
    description: "Fictieve woning voor de demo. Tussenwoning met achtertuin in een rustige wijk.",
  },
  {
    source: "example-portal-b",
    id: "DV-2003",
    street: "Concepthof",
    houseNumber: "21",
    city: "Eindhoven",
    municipality: "Eindhoven",
    province: "Noord-Brabant",
    lat: 51.4416,
    lng: 5.4697,
    segment: "midden",
    allocationModel: "motivatie",
    priceNet: 1020,
    serviceCosts: 55,
    rooms: 3,
    bedrooms: 2,
    areaM2: 78,
    dwellingType: "Appartement",
    dwellingCategory: "apartment",
    energyLabel: "A",
    constructionYear: 2021,
    floor: 5,
    availableFrom: "2026-11-01",
    publishedAt: "2026-09-28T12:00:00.000Z",
    labels: ["sleutelberoepen", "motivatie_gevraagd"],
    notices: ["Voorrang voor sleutelberoepen"],
    reactionsCount: 42,
    description:
      "Fictieve woning voor de demo. Nieuw appartement, korte motivatie gevraagd bij je reactie.",
  },
  {
    source: "example-portal",
    id: "VW-1008",
    street: "Fantasiestraat",
    houseNumber: "60",
    city: "Groningen",
    municipality: "Groningen",
    province: "Groningen",
    lat: 53.2194,
    lng: 6.5665,
    segment: "social",
    allocationModel: "direct",
    priceNet: 520,
    serviceCosts: 25,
    rooms: 1,
    bedrooms: 0,
    areaM2: 32,
    dwellingType: "Studio",
    dwellingCategory: "studio",
    energyLabel: "C",
    constructionYear: 1979,
    floor: 2,
    availableFrom: "2026-10-15",
    publishedAt: "2026-10-01T06:30:00.000Z",
    reactionsCount: null,
    description:
      "Fictieve woning voor de demo. Studio met eigen keuken en badkamer, direct te huur.",
  },
  {
    source: "example-portal",
    id: "VW-1009",
    street: "Gedachtelaan",
    houseNumber: "33",
    city: "Maastricht",
    municipality: "Maastricht",
    province: "Limburg",
    lat: 50.8514,
    lng: 5.691,
    segment: "social",
    allocationModel: "inschrijfduur",
    priceNet: 680,
    serviceCosts: 35,
    rooms: 3,
    bedrooms: 2,
    areaM2: 66,
    dwellingType: "Portiekwoning",
    dwellingCategory: "apartment",
    energyLabel: "D",
    constructionYear: 1958,
    floor: 1,
    availableFrom: null,
    publishedAt: "2026-09-27T09:15:00.000Z",
    notices: ["Kernbinding: voorrang voor inwoners van de gemeente"],
    eligibility: {
      minIncome: null,
      maxIncome: null,
      minAge: null,
      maxAge: null,
      minHousehold: null,
      maxHousehold: null,
      localBindingPriority: true,
    },
    reactionsCount: 120,
    description: "Fictieve woning voor de demo. Portiekwoning op loopafstand van de Maas.",
  },
];

/** The seeds, expanded to the canonical schema every adapter produces. */
export function demoListings(): CanonicalListing[] {
  return SEEDS.map((s) => {
    const host = `${s.source}.example.com`;
    const base: Omit<CanonicalListing, "rawHash"> = {
      sourceSlug: s.source,
      sourceListingId: s.id,
      canonicalKey: canonicalKey({
        postcode: null,
        houseNumber: null,
        fallback: `${s.source}:${s.id}`,
      }),
      url: `https://${host}/woning/${s.id}`,
      applyUrl: `https://${host}/woning/${s.id}/reageren`,
      title: `${s.street} ${s.houseNumber}, ${s.city}`,
      segment: s.segment,
      segmentReason: "demo: fictional listing, segment set by hand",
      allocationModel: s.allocationModel,
      closesAfterFirstReaction: s.allocationModel === "direct",
      priceNet: s.priceNet,
      priceTotal: s.priceNet + s.serviceCosts,
      serviceCosts: s.serviceCosts,
      address: {
        street: s.street,
        houseNumber: s.houseNumber,
        houseNumberAddition: null,
        postcode: null,
        city: s.city,
        municipality: s.municipality,
        province: s.province,
        country: "NL",
      },
      location: { lat: s.lat, lng: s.lng },
      rooms: s.rooms,
      bedrooms: s.bedrooms,
      areaM2: s.areaM2,
      dwellingType: s.dwellingType,
      dwellingCategory: s.dwellingCategory,
      energyLabel: s.energyLabel,
      constructionYear: s.constructionYear,
      floor: s.floor,
      availableFrom: s.availableFrom,
      availableFromText: s.availableFrom ? null : "In overleg",
      publishedAt: s.publishedAt,
      // No deadline: a fixed date would show as "closed" to anyone opening the demo later.
      closesAt: null,
      labels: s.labels ?? [],
      targetGroups: [],
      operator: {
        code: null,
        name:
          s.source === "example-portal"
            ? "Woonstichting Voorbeeld (fictief)"
            : "Demo Verhuur (fictief)",
      },
      registrationRequired: s.source === "example-portal",
      huurtoeslagPossible: s.segment === "social",
      photos: [],
      thumbnail: null,
      isNewBuild: (s.labels ?? []).includes("nieuwbouw"),
      isExchange: false,
      notices: s.notices ?? [],
      eligibility: s.eligibility ?? null,
      reactionsCount: s.reactionsCount,
      description: s.description,
    };
    return { ...base, rawHash: stableHash(base) };
  });
}
