// AUTO-GENERATED by `pnpm legal:generate` (src/lib/legal/generate.mjs). Do not edit by hand.
// Source of truth: docs/legal/*.md. Documents with unresolved placeholders or REVIEW markers
// come out of here as `status: "blocked"` and WITHOUT text; see generate.mjs and types.ts.

import type { LegalContent } from "./types";

export const LEGAL_CONTENT: LegalContent = {
  generatedAt: "2026-09-11T14:43:30.012Z",
  contentHash: "7206764201b3474c",
  docs: [
    {
      kind: "terms",
      locale: "nl",
      source: "docs/legal/terms.nl.md",
      sourceHash: "b6254b440f26ecca",
      title: "Gebruiksvoorwaarden PAPA RENT",
      status: "blocked",
      blockers: [
        {
          kind: "placeholder",
          token: "[adres]",
          occurrences: 3,
        },
        {
          kind: "placeholder",
          token: "[datum]",
          occurrences: 1,
        },
        {
          kind: "placeholder",
          token: "[email]",
          occurrences: 6,
        },
        {
          kind: "placeholder",
          token: "[KvK-nummer]",
          occurrences: 3,
        },
        {
          kind: "review",
          occurrences: 6,
        },
      ],
    },
    {
      kind: "terms",
      locale: "en",
      source: "docs/legal/terms.en.md",
      sourceHash: "05ee971c66a6f5e7",
      title: "PAPA RENT — Terms of Use",
      status: "blocked",
      blockers: [
        {
          kind: "placeholder",
          token: "[adres]",
          occurrences: 3,
        },
        {
          kind: "placeholder",
          token: "[date]",
          occurrences: 1,
        },
        {
          kind: "placeholder",
          token: "[email]",
          occurrences: 6,
        },
        {
          kind: "placeholder",
          token: "[KvK-nummer]",
          occurrences: 3,
        },
        {
          kind: "review",
          occurrences: 6,
        },
      ],
    },
    {
      kind: "privacy",
      locale: "nl",
      source: "docs/legal/privacy.nl.md",
      sourceHash: "ef2720630e9d9474",
      title: "Privacyverklaring PAPA RENT",
      status: "blocked",
      blockers: [
        {
          kind: "placeholder",
          token: "[adres]",
          occurrences: 2,
        },
        {
          kind: "placeholder",
          token: "[datum]",
          occurrences: 1,
        },
        {
          kind: "placeholder",
          token: "[email]",
          occurrences: 6,
        },
        {
          kind: "placeholder",
          token: "[KvK-nummer]",
          occurrences: 2,
        },
        {
          kind: "review",
          occurrences: 7,
        },
      ],
    },
    {
      kind: "privacy",
      locale: "en",
      source: "docs/legal/privacy.en.md",
      sourceHash: "046b3c5a859afce0",
      title: "PAPA RENT — Privacy Policy",
      status: "blocked",
      blockers: [
        {
          kind: "placeholder",
          token: "[adres]",
          occurrences: 2,
        },
        {
          kind: "placeholder",
          token: "[date]",
          occurrences: 1,
        },
        {
          kind: "placeholder",
          token: "[email]",
          occurrences: 6,
        },
        {
          kind: "placeholder",
          token: "[KvK-nummer]",
          occurrences: 2,
        },
        {
          kind: "review",
          occurrences: 7,
        },
      ],
    },
    {
      kind: "disclaimer",
      locale: "nl",
      source: "docs/legal/disclaimer.nl.md",
      sourceHash: "19fcd043898b2adf",
      title: "Even dit, voordat je begint",
      status: "published",
      blocks: [
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "PAPA RENT is een meldingsdienst, geen woningbemiddelaar.",
            },
            {
              text: "\nWij waarschuwen je zodra er passend aanbod verschijnt. Reageren doe je zelf, op de site van de verhuurder of het woonruimteverdeelsysteem.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "Wij reageren nooit namens jou.",
            },
            {
              text: "\nWij vragen nooit je inloggegevens van een woningsite, nooit je BSN en nooit documenten zoals loonstroken of een kopie ID. Vraagt iemand daar namens ons om: dat zijn wij niet.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "Wij rekenen geen bemiddelingskosten.",
            },
            {
              text: "\nDat mag ook niet in Nederland als je namens een verhuurder werkt — en dat doen wij niet. Betaal je ooit voor PAPA RENT, dan betaal je voor meldingen en filters, nooit voor een woning.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "Wij kunnen niet garanderen dat je alles ziet, of dat je het op tijd ziet.",
            },
            {
              text: "\nWoningsites veranderen, gaan offline of halen advertenties weg. Wij missen soms aanbod of zijn een paar minuten later dan de bron.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "De bron is altijd leidend.",
            },
            {
              text: "\nControleer prijs, oppervlakte, sluitingsdatum en voorwaarden altijd op de site van de verhuurder voordat je reageert.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "Of je in aanmerking komt, bepalen wij niet.",
            },
            {
              text: "\nWij filteren op basis van wat jij invult (leeftijd, en optioneel je inkomensband en huishoudgrootte). Alleen de corporatie, de verhuurder en de gemeente beslissen wie een woning krijgt.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "Wij verzamelen zo min mogelijk over jou.",
            },
            {
              text: "\nE-mail, geboortedatum (nodig voor 55+, jongeren- en studentenwoningen) en je zoekopdrachten. Meer niet, tenzij je zelf kiest om extra filters in te vullen. Alles is met één tik te exporteren of te wissen.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "Je moet 16 jaar of ouder zijn.",
            },
          ],
        },
        {
          type: "rule",
        },
        {
          type: "paragraph",
          spans: [
            {
              text: "Door verder te gaan ga je akkoord met de ",
            },
            {
              href: "https://example.com/voorwaarden",
              text: "Gebruiksvoorwaarden",
            },
            {
              text: " en de ",
            },
            {
              href: "https://example.com/privacy",
              text: "Privacyverklaring",
            },
            {
              text: ".",
            },
          ],
        },
      ],
    },
    {
      kind: "disclaimer",
      locale: "en",
      source: "docs/legal/disclaimer.en.md",
      sourceHash: "f6f0ac22dad02611",
      title: "One thing before you start",
      status: "published",
      blocks: [
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "PAPA RENT is an alert service, not a housing agent.",
            },
            {
              text: "\nWe tell you the moment matching supply appears. You apply yourself, on the landlord's or the allocation system's own site.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "We never apply on your behalf.",
            },
            {
              text: "\nWe never ask for your login details for a housing site, never for your BSN, and never for documents such as payslips or a copy of your ID. If someone asks for those on our behalf, it is not us.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "We charge no mediation fees (",
            },
            {
              bold: true,
              italic: true,
              text: "bemiddelingskosten",
            },
            {
              bold: true,
              text: ").",
            },
            {
              text: "\nDutch law forbids that when you act for a landlord — and we do not act for landlords. If you ever pay for PAPA RENT, you pay for alerts and filters, never for a home.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "We cannot guarantee you see everything, or see it in time.",
            },
            {
              text: "\nHousing sites change, go offline or remove listings. Sometimes we miss supply, or we are a few minutes behind the source.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "The source always prevails.",
            },
            {
              text: "\nAlways check price, size, closing date and conditions on the landlord's own site before you apply.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "We do not decide whether you qualify.",
            },
            {
              text: "\nWe filter on what you tell us (your age, and optionally your income band and household size). Only the housing corporation, the landlord and the municipality decide who gets a home.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "We collect as little as possible about you.",
            },
            {
              text: "\nYour email, your date of birth (needed for 55+, youth and student homes) and your saved searches. Nothing more, unless you choose to add extra filters. Everything can be exported or erased with one tap.",
            },
          ],
        },
        {
          type: "paragraph",
          spans: [
            {
              bold: true,
              text: "You must be 16 or older.",
            },
          ],
        },
        {
          type: "rule",
        },
        {
          type: "paragraph",
          spans: [
            {
              text: "By continuing you agree to the ",
            },
            {
              href: "https://example.com/terms",
              text: "Terms of Use",
            },
            {
              text: " and the ",
            },
            {
              href: "https://example.com/privacy",
              text: "Privacy Policy",
            },
            {
              text: ".",
            },
          ],
        },
      ],
    },
    {
      kind: "bot",
      locale: "nl",
      source: "docs/legal/bot-page.nl.md",
      sourceHash: "91452927a292cee5",
      title: "PapaRentBot — informatie voor websitebeheerders",
      status: "blocked",
      blockers: [
        {
          kind: "placeholder",
          token: "[adres]",
          occurrences: 2,
        },
        {
          kind: "placeholder",
          token: "[datum]",
          occurrences: 1,
        },
        {
          kind: "placeholder",
          token: "[email]",
          occurrences: 9,
        },
        {
          kind: "placeholder",
          token: "[KvK-nummer]",
          occurrences: 2,
        },
        {
          kind: "review",
          occurrences: 1,
        },
      ],
    },
    {
      kind: "bot",
      locale: "en",
      source: "docs/legal/bot-page.en.md",
      sourceHash: "76d8f86dca47c290",
      title: "PapaRentBot — information for website operators",
      status: "blocked",
      blockers: [
        {
          kind: "placeholder",
          token: "[adres]",
          occurrences: 2,
        },
        {
          kind: "placeholder",
          token: "[date]",
          occurrences: 1,
        },
        {
          kind: "placeholder",
          token: "[email]",
          occurrences: 9,
        },
        {
          kind: "placeholder",
          token: "[KvK-nummer]",
          occurrences: 2,
        },
        {
          kind: "review",
          occurrences: 1,
        },
      ],
    },
  ],
};
